[2024-04-29T19:01:01.170+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T19:01:01.190+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_v6.train scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T19:01:01.197+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_v6.train scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T19:01:01.198+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T19:01:01.209+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train> on 2024-04-28 00:00:00+00:00
[2024-04-29T19:01:01.217+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_model_v6', 'train', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_train.py', '--cfg-path', '/tmp/tmpt7r3l3rk']
[2024-04-29T19:01:01.219+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask train
[2024-04-29T19:01:01.220+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1646) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T19:01:01.221+0000] {standard_task_runner.py:63} INFO - Started process 1663 to run task
[2024-04-29T19:01:01.257+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model_v6.train scheduled__2024-04-28T00:00:00+00:00 [running]> on host d1f0cdf1c56a
[2024-04-29T19:01:01.320+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='train_model_v6' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T19:01:01.321+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T19:01:01.347+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_train.py:46 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T19:01:01.698+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T19:01:01.699+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_train.py", line 77, in train_model
    cur.execute(sql)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
LINE 3: ...20, "subsample": 0.5, "col_sample_bytree": 0.5}', '{"train":...
                                                             ^
DETAIL:  Token "(" is invalid.
CONTEXT:  JSON data, line 1: {"train": (...

[2024-04-29T19:01:01.710+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model_v6, task_id=train, execution_date=20240428T000000, start_date=20240429T190101, end_date=20240429T190101
[2024-04-29T19:01:01.721+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task train (invalid input syntax for type json
LINE 3: ...20, "subsample": 0.5, "col_sample_bytree": 0.5}', '{"train":...
                                                             ^
DETAIL:  Token "(" is invalid.
CONTEXT:  JSON data, line 1: {"train": (...
; 1663)
[2024-04-29T19:01:01.757+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T19:01:01.770+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T19:01:01.773+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
