[2024-04-29T17:17:32.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T17:17:32.183+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T17:17:32.191+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T17:17:32.194+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T17:17:32.206+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): processed> on 2024-04-28 00:00:00+00:00
[2024-04-29T17:17:32.212+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_data_v11', 'processed', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_processed.py', '--cfg-path', '/tmp/tmp00k12xdj']
[2024-04-29T17:17:32.214+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1164) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T17:17:32.215+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask processed
[2024-04-29T17:17:32.215+0000] {standard_task_runner.py:63} INFO - Started process 1170 to run task
[2024-04-29T17:17:32.253+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [running]> on host 15fcc90b2790
[2024-04-29T17:17:32.315+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='fill_data_v11' AIRFLOW_CTX_TASK_ID='processed' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T17:17:32.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T17:17:32.343+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_raw_processed.py:45 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T17:17:41.643+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T17:17:41.644+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T17:17:41.650+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fill_data_v11, task_id=processed, execution_date=20240428T000000, start_date=20240429T171732, end_date=20240429T171741
[2024-04-29T17:17:41.684+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T17:17:41.696+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T17:17:41.700+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-29T18:44:57.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T18:44:57.827+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T18:44:57.836+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T18:44:57.837+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T18:44:57.851+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): processed> on 2024-04-28 00:00:00+00:00
[2024-04-29T18:44:57.863+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_data_v11', 'processed', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_processed.py', '--cfg-path', '/tmp/tmp48z_wve4']
[2024-04-29T18:44:57.870+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask processed
[2024-04-29T18:44:57.869+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=380) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T18:44:57.871+0000] {standard_task_runner.py:63} INFO - Started process 382 to run task
[2024-04-29T18:44:57.916+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [running]> on host d1f0cdf1c56a
[2024-04-29T18:44:57.995+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='fill_data_v11' AIRFLOW_CTX_TASK_ID='processed' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T18:44:57.996+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T18:44:58.082+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_raw_processed.py:43 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T18:45:14.155+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T18:45:14.158+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T18:45:14.172+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fill_data_v11, task_id=processed, execution_date=20240428T000000, start_date=20240429T184457, end_date=20240429T184514
[2024-04-29T18:45:14.210+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T18:45:14.241+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T18:45:14.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-29T19:55:39.063+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T19:55:39.286+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T19:55:39.297+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T19:55:39.298+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T19:55:39.316+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): processed> on 2024-04-28 00:00:00+00:00
[2024-04-29T19:55:39.336+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_data_v11', 'processed', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_processed.py', '--cfg-path', '/tmp/tmpyvbs5yot']
[2024-04-29T19:55:39.339+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=848) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T19:55:39.340+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask processed
[2024-04-29T19:55:39.341+0000] {standard_task_runner.py:63} INFO - Started process 850 to run task
[2024-04-29T19:55:39.420+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_data_v11.processed scheduled__2024-04-28T00:00:00+00:00 [running]> on host d4bc696c9a4e
[2024-04-29T19:55:39.543+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='fill_data_v11' AIRFLOW_CTX_TASK_ID='processed' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T19:55:39.545+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T19:55:39.623+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_raw_processed.py:43 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T19:56:01.021+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T19:56:01.023+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T19:56:01.032+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fill_data_v11, task_id=processed, execution_date=20240428T000000, start_date=20240429T195539, end_date=20240429T195601
[2024-04-29T19:56:01.069+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T19:56:01.084+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T19:56:01.086+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
